version: '3.8'

services:
  app:
    image: webdevops/php-nginx-dev:7.4
    restart: on-failure
    container_name: symfonychat-app
    ports:
      - "8085:80"
      - "44385:443"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      XDEBUG_CLIENT_HOST: host.docker.internal      
      PHP_DATE_TIMEZONE: Europe/Berlin
    networks:
      - default
      - proxy

networks:
  proxy:
    name: proxy
    external: true
